name: elasticsearch
services:
  elasticsearch:
    image: elasticsearch:8.6.2
    environment:
      - ES_SETTING_DISCOVERY_TYPE=single-node
      - ES_SETTING_NODE_STORE_ALLOW__MMAP=false
      - ES_SETTING_XPACK_SECURITY_ENABLED=false
      - LICENSE=basic
    deploy:
      resources:
        limits:
          memory: 1g
    logging:
      options:
        max-size: 512m
    expose:
      - 9200
      - 9300
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    restart: unless-stopped
    x-casaos:
      author: tigerinus
      category: Developer
      container:
        port_map: "9200"
      description:
        en_US: Elasticsearch is a distributed, RESTful search and analytics engine capable of addressing a growing number of use cases.
      developer: elastic
      icon: https://d1q6f0aelx0por.cloudfront.net/product-logos/library-elasticsearch-logo.png
      title:
        en_US: Elasticsearch
  kibana:
    image: kibana:8.6.2
    environment:
      - DATA_SEARCH_SESSIONS_ENABLED=false
      - TELEMETRY_OPTIN=false
      - XPACK_FLEET_AGENTS_ENABLED=false
      - XPACK_REPORTING_ENABLED=false
    deploy:
      resources:
        limits:
          memory: 768m
    ports:
      - 5601:5601
    volumes:
      - kibana_data:/usr/share/kibana/data
    depends_on:
      - elasticsearch
    restart: unless-stopped
    x-casaos:
      author: tigerinus
      category: Developer
      container:
        port_map: "5601"
      description:
        en_US: Kibana lets you visualize your Elasticsearch data and navigate the Elastic Stack
      developer: elastic
      icon: https://d1q6f0aelx0por.cloudfront.net/product-logos/library-kibana-logo.png
      title:
        en_US: Kibana

volumes:
  elasticsearch_data:
  kibana_data:

x-casaos:
  architectures:
    - amd64
    - arm64
  main_app: kibana
