name: elasticsearch
services:
  elasticsearch:
    image: elasticsearch:8.6.2
    environment:
      - node.store.allow_mmap=false
      - discovery.type=single-node
      - xpack.security.enabled=false
    deploy:
      resources:
        reservations:
          memory: 1g
    logging:
      options:
        max-size: 512m
    expose:
      - 9200
      - 9300
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    x-casaos:
      author: tigerinus
      category: Developer
      container:
        port_map: "9200"
      description:
        en_US: Elasticsearch is a distributed, RESTful search and analytics engine capable of addressing a growing number of use cases.
      developer: elastic
      icon: https://d1q6f0aelx0por.cloudfront.net/product-logos/library-elasticsearch-logo.png
      tagline:
        en_US: a distributed, RESTful search and analytics engine capable of addressing a growing number of use cases.
      title:
        en_US: Elasticsearch
  kibana:
    image: kibana:8.6.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    deploy:
      resources:
        reservations:
          memory: 512m
    ports:
      - 5601:5601
    volumes:
      - kibana_data:/usr/share/kibana/data
    depends_on:
      - elasticsearch
    x-casaos:
      author: tigerinus
      category: Developer
      container:
        port_map: "5601"
      icon: https://d1q6f0aelx0por.cloudfront.net/product-logos/library-kibana-logo.png


volumes:
  elasticsearch_data:
  kibana_data:

x-casaos:
  architectures:
    - amd64
    - arm64
  main_app: elasticsearch
