name: elasticsearch
services:
  elasticsearch:
    image: elasticsearch:8.6.2
    deploy:
      resources:
        reservations:
          memory: 1g
    networks:
      - elasticsearch
    logging:
      options:
        max-size: 512m
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - /opt/elasticsearch/config:/usr/share/elasticsearch/config
      - /opt/elasticsearch/data:/usr/share/elasticsearch/data
    restart: unless-stopped
  kibana:
    image: kibana:8.6.2
    deploy:
      resources:
        reservations:
          memory: 512m
    networks:
      - elasticsearch
    ports:
      - 5601:5601
    volumes:
      - /opt/kibana/config:/usr/share/kibana/config
      - /opt/kibana/data:/usr/share/kibana/data
    restart: unless-stopped
