name: elasticsearch
services:
  elasticsearch:
    image: elasticsearch:8.6.2
    deploy:
      resources:
        reservations:
          memory: 1g
    networks:
      - elasticsearch
    logging:
      options:
        max-size: 512m
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - /opt/elasticsearch/config:/usr/share/elasticsearch/config
      - /opt/elasticsearch/data:/usr/share/elasticsearch/data
    restart: unless-stopped
    x-casaos:
      author: tigerinus
      category: Developer
      container:
        port_map: "5601"
      description:
        en_US: Elasticsearch is a distributed, RESTful search and analytics engine capable of addressing a growing number of use cases.
      developer: elastic
      icon: https://d1q6f0aelx0por.cloudfront.net/product-logos/library-kibana-logo.png
      tagline:
        en_US: a distributed, RESTful search and analytics engine capable of addressing a growing number of use cases.
      title:
        en_US: Elasticsearch
  kibana:
    image: kibana:8.6.2
    deploy:
      resources:
        reservations:
          memory: 512m
    networks:
      - elasticsearch
    ports:
      - 5601:5601
    volumes:
      - /opt/kibana/config:/usr/share/kibana/config
      - /opt/kibana/data:/usr/share/kibana/data
    restart: unless-stopped

networks:
  elasticsearch:
    driver: overlay

x-casaos:
  architectures:
    - amd64
    - arm64
  main_app: elasticsearch
